[package]
name = "rustydebug"
version = "0.1.0"
authors = ["Walter de Jong <walter@heiho.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isatty = "0.1"
